### ISSUE TITLE
Cannot read words on homepage

### ISSUE THREAD

**Issue by honeysaini21** [IqbalKaur/iqbalkaur#1]
User cannot read the text "Sharing what I know" on the homepage.
The text overlap with the website design white text on white design which is unreadable.
![screen shot 2015-01-21 at 6 16 24 pm](https://cloud.githubusercontent.com/assets/10642788/5847303/b20a16f2-a199-11e4-8357-c73dbbbff61a.png)

``` html
<span class="subheading">
    Sharing what I know.</span>
```

**Comment by IqbalKaur** [comment]
Thanks for reporting me this issue. I am gonna fix it soon.
